### ISSUE TITLE
Перейти на специальный инструмент для тестов

### ISSUE THREAD

**Issue by Termonoid** [catspace-dev/unicheckbot#27]
Ну раз уж ты заставил меня написать этот трешак, было бы неплохо затащить нормальный инструмент для тестирования

**Comment by kiriharu** [comment]
В poetry есть возможность запускать тесты.

**Comment by Termonoid** [comment]
> В poetry есть возможность запускать тесты.

А что запускать то епта, запускать нечего, там тестит самописный костыль
